parametros padrao e instalador linux

diff --git a/git-flow-betafix b/git-flow-betafix
--- a/git-flow-betafix
+++ b/git-flow-betafix
@@ -217,7 +217,7 @@ cmd_publish() {
 }
 
 cmd_finish() {
-  DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
+  DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
   DEFINE_boolean sign false "sign the release tag cryptographically" s
   DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
   DEFINE_string message "" "use the given tag message" m
@@ -248,17 +248,21 @@ cmd_finish() {
     require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
   fi
 
-  # try to merge into beta
+  # try to merge into develop
   # in case a previous attempt to finish this release branch has failed,
-  # but the merge into beta was successful, we skip it now
-  if ! git_is_branch_merged_into "$BRANCH" "$BETA_BRANCH"; then
-    git checkout "$BETA_BRANCH" || \
-      die "Could not check out $BETA_BRANCH."
+  # but the merge into develop was successful, we skip it now
+  if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+    git checkout "$DEVELOP_BRANCH" || \
+      die "Could not check out $DEVELOP_BRANCH."
+
+    # TODO: Actually, accounting for 'git describe' pays, so we should
+    # ideally git merge --no-ff $tagname here, instead!
     git merge --no-ff "$BRANCH" || \
       die "There were merge conflicts."
       # TODO: What do we do now?
   fi
 
+  
   if noflag notag; then
     # try to tag the release
     # in case a previous attempt to finish this release branch has failed,
@@ -274,19 +278,19 @@ cmd_finish() {
     fi
   fi
 
-  # try to merge into develop
+# try to merge into beta
   # in case a previous attempt to finish this release branch has failed,
-  # but the merge into develop was successful, we skip it now
-  if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-    git checkout "$DEVELOP_BRANCH" || \
-      die "Could not check out $DEVELOP_BRANCH."
-
-    # TODO: Actually, accounting for 'git describe' pays, so we should
-    # ideally git merge --no-ff $tagname here, instead!
+  # but the merge into beta was successful, we skip it now
+  if ! git_is_branch_merged_into "$BRANCH" "$BETA_BRANCH"; then
+    git checkout "$BETA_BRANCH" || \
+      die "Could not check out $BETA_BRANCH."
     git merge --no-ff "$BRANCH" || \
       die "There were merge conflicts."
       # TODO: What do we do now?
   fi
+
+  git checkout "$BETA_BRANCH" || \
+      die "Could not check out $MASTER_BRANCH."
 
   # delete branch
   if noflag keep; then
