betafix and hotfix for beta

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -217,13 +217,13 @@ cmd_publish() {
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
 	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean notag false "don't tag this release" n
+	DEFINE_boolean notag true "don't tag this release" n
 	parse_args "$@"
 	require_version_arg
 
@@ -240,6 +240,8 @@ cmd_finish() {
 		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
 		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+		git fetch -q "$ORIGIN" "$BETA_BRANCH" || \
+		  die "Could not fetch $BETA_BRANCH from $ORIGIN."	
 	fi
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
@@ -247,7 +249,9 @@ cmd_finish() {
 	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
-
+	if has "$ORIGIN/$BETA_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$BETA_BRANCH" "$ORIGIN/$BETA_BRANCH"
+	fi
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into master was successful, we skip it now
@@ -258,6 +262,8 @@ cmd_finish() {
 		  die "There were merge conflicts."
 		  # TODO: What do we do now?
 	fi
+
+
 
 	if noflag notag; then
 		# try to tag the release
@@ -288,6 +294,17 @@ cmd_finish() {
 		  # TODO: What do we do now?
 	fi
 
+	# try to merge into beta
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$BETA_BRANCH"; then
+		git checkout "$BETA_BRANCH" || \
+		  die "Could not check out $BETA_BRANCH."
+		git merge --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+
 	# delete branch
 	if noflag keep; then
 		git branch -d "$BRANCH"
@@ -298,6 +315,8 @@ cmd_finish() {
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		git push "$ORIGIN" "$BETA_BRANCH" || \
+			die "Could not push to $MASTER_BRANCH from $ORIGIN."		
 		if noflag notag; then
 			git push --tags "$ORIGIN" || \
 				die "Could not push tags to $ORIGIN."
@@ -312,13 +331,14 @@ cmd_finish() {
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
 	fi
 	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
+	echo "- Hotfix branch has been back-merged into '$BETA_BRANCH'"
 	if flag keep; then
 		echo "- Hotfix branch '$BRANCH' is still available"
 	else
 		echo "- Hotfix branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$DEVELOP_BRANCH', '$BETA_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
 	fi
 	echo
 }
